# Generated by Django 6.0.7 on 2026-07-10 10:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flower', models.CharField(max_length=20)),
                ('rate', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('qut', models.IntegerField()),
                ('imge', models.ImageField(upload_to='products/')),
                ('final_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('house_no', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=90)),
                ('date', models.DateField(default=datetime.datetime(2026, 7, 10, 10, 14, 17, 394826, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime(2026, 7, 10, 10, 14, 17, 393524, tzinfo=datetime.timezone.utc))),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150)),
                ('Color', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2026, 7, 10, 10, 14, 17, 394150, tzinfo=datetime.timezone.utc))),
                ('detales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Flower_ditales', to='app.add_product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
