# Generated by Django 6.0.7 on 2026-07-10 10:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adders',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 10, 10, 16, 28, 468782, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 10, 10, 16, 28, 467567, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detales',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 10, 10, 16, 28, 468166, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
