# Generated by Django 6.0.7 on 2026-07-10 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_adders_date_alter_cart_date_alter_detales_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adders',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 10, 14, 55, 8, 645206, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 10, 14, 55, 8, 642263, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detales',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 10, 14, 55, 8, 643533, tzinfo=datetime.timezone.utc)),
        ),
    ]
