# Generated by Django 6.0.3 on 2026-07-11 10:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_adders_date_alter_cart_date_alter_detales_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='adders',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 11, 10, 9, 18, 956723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 11, 10, 9, 18, 956723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detales',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 11, 10, 9, 18, 956723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.adders'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
