# Generated by Django 6.0.7 on 2026-07-29 06:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_adders_date_alter_cart_date_alter_detales_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adders',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 29, 6, 14, 28, 766796, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 29, 6, 14, 28, 765587, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detales',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 29, 6, 14, 28, 766173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
