# Generated by Django 6.0.7 on 2026-07-29 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_adders_date_alter_cart_date_alter_detales_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='adders',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 29, 6, 51, 14, 365355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 29, 6, 51, 14, 364100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detales',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 29, 6, 51, 14, 364676, tzinfo=datetime.timezone.utc)),
        ),
    ]
