# Generated by Django 6.0.1 on 2026-08-06 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_adders_date_alter_cart_date_alter_detales_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adders',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 8, 6, 11, 13, 37, 999771, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 8, 6, 11, 13, 37, 998692, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detales',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 8, 6, 11, 13, 37, 999223, tzinfo=datetime.timezone.utc)),
        ),
    ]
