# Generated by Django 6.0.7 on 2026-10-06 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_adders_date_alter_cart_date_alter_detales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adders',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='detales',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
